services:
  db:
    image: mysql:8.0.38
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: dongthucvat
    ports:
      - "3306:3306"
    volumes:
      - ./data/dongthucvat.sql:/docker-entrypoint-initdb.d/dongthucvat.sql
    networks:
      - mysql_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  mysql_network:
    driver: bridge
